### ISSUE TITLE
Add Czech

### ISSUE THREAD

**Issue by VojtechDostal** [hatnote/hashtag-search#12]
Hi, could you please add Czech Wikipedia (cs) to the list of supported wikis? We'll be starting with a 1lib1ref campaign next year. Thank you.

**Comment by Sadads** [comment]
@slaporte @mahmoud do you think you could add this? We are starting to get volunteer leaders lined up for the campaign, and there are going to be a few more requests coming up as well.

**Comment by urbanecm** [comment]
Doesn't cswiki work? https://tools.wmflabs.org/hashtags/search/d%C3%A1rek?lang=cs as one example. I think we can close this report.

**Comment by slaporte** [comment]
We're collecting revisions from Czech Wikipedia now.
