### ISSUE TITLE
Option to change time frame

### ISSUE THREAD

**Issue by uyscuti-wiki** [hatnote/hashtag-search#18]
Currently the tool shows the statistics for all the hashtags from the date it first appeared. To be able to manually set time frame would be a nice addition.

**Comment by Samwalton9** [comment]
This should be done in https://github.com/Samwalton9/hashtag-search/commit/64fcab59c6dce3d4319e934e1453c5552cc39353

It can be tested at https://tools.wmflabs.org/hashtags-test.

**Comment by Samwalton9** [comment]
Known issues:

* Date should be inclusive (filtering for 1st to 19th should include the 19th).
* Some links on the test site direct back to the main tool (not really an issue)
* "No revisions tagged with # (yet)" message should say "in this date range" if a start or end date is present and no entries are returned.

**Comment by strainu** [comment]
Thank you @Samwalton9 ! This will be great for repeated events such as #1Lib1Ref

**Comment by Samwalton9** [comment]
And to clarify: The tool only has data from the 18th and 19th as I'm having to use a fresh database and haven't set up regular data collection.

**Comment by slaporte** [comment]
Deployed Sam's fix from #23.
