### ISSUE TITLE
Tool no longer finding current hashtags?

### ISSUE THREAD

**Issue by jessamynwest** [hatnote/hashtag-search#26]
Since the update last night, the tool seems to no longer be picking up newer edits? Both the CSV and the display are showing edits from last night (US time) and not edits made today.

**Comment by Samwalton9** [comment]
I cant take a look at this properly until tomorrow but I suspect it could be because this change wasn't also made to hashtags' log.py: https://github.com/hatnote/hashtag-search/commit/2963e6adeec700269599796dcfc5693f8457622d

**Comment by slaporte** [comment]
@Samwalton9 That's right -- I just deployed a fix at hatnote/hashtags@35cb181. Backfilling data now, and I'll keep this open until we have it all. Thanks!

**Comment by jessamynwest** [comment]
@slaporte Oh thank you -- we're right near a milestone, thanks for your speedy attention.

**Comment by slaporte** [comment]
Whew, it's now fixed. I've backfilled all the data from yesterday.

Thanks both!
