### ISSUE TITLE
Hashtags on Punjabi Wikipedia

### ISSUE THREAD

**Issue by satdeepgill** [hatnote/hashtag-search#4]
We are hoping to start an edit-a-thon from 1st April. Let me know if this is possible.

**Comment by slaporte** [comment]
It now [supports Punjabi](http://tools.wmflabs.org/hashtags/search/?lang=pa). Good luck with the edit-a-thon!

**Comment by satdeepgill** [comment]
Thanks a lot.

Regards
Satdeep Gill

**Comment by Sadads** [comment]
This is brilliant!

Cheers,

Alex
